translations:
  load: "This command is used to load a model. To get the list of all the available models, use /model list.\nThe scale is a number where 1.0 is the base scale.\nIf no pattern is set, the blocks from the schematics will be used."
  roll: "Use this command to set the roll value of the next part you paste."
  adjust: "Use this command to adjust the rotation of a certain part."
  end: "Use this command to complete your model."
  list: "Use this command to list the available models."
  undo: "Revert the last change you made."
  cancel: "Stops the model creation process entirely."
  init: "Use this command to initialize the available models. (Load them into memory to use them later)"
  invalid: "&cUnknown Command, type /model help for more"
  no-permission: "&cYou don't have the permission to use that command."
  player-only: "This command can only be used by a player."
  not-enough-args: "&cThere isn't enough arguments"
  yrp-number: "&cYaw, roll, pitch must be numbers."
  not-creating: "&cYou aren't creating a model, you can't use this command now."
  part-modified: "&aThe part was successfully modified, the new values are:"
  not-completed: "&cYour model isn't completed yet, you cannot validate it."
  init-success: "&aModel initialization was successful!"
  init-failed: "&cModel initialization failed! Check console for errors."
  init-already: "&aAlready initialized!"
  loaded-models: "&eThe loaded models are:"
  scale-not-number: "&cScale must be a number."
  scale-too-big: "&cThe scale is too big, the maximum allowed is 2.0."
  pattern-error: "&cUnable to parse the pattern:"
  already-creating: "&cYou can't load a new model, you're already creating one."
  model-not-found: "&cModel not found. Use /model list to list the available models."
  model-loaded1: "&aModel successfully loaded."
  model-loaded2: "&ePlace a part by clicking in the direction you want it to be facing."
  model-loaded3: "&eYou can modify the roll value of the next part by using &f&o%cmd_usage%"
  rotation-not-number: "&cRotation (roll) must be a number."
  roll-success: "&aOperation successful, the next part you paste will have a roll value of %roll%"
  help: "========= Help ========="
  no-more-to-paste1: "&cThere isn't any part left to paste."
  no-more-to-paste2: "&eYou can either cancel your last part, adjust any of them with &f/model adjust &eor validate the model as it is with &f/model end."
  paste-all1: "&aYou have successfully placed all the part."
  paste-all2: "&eYou can now validate the model as it is with &f%cmd_usage%"
  paste-all3: "&eOr you can adjust the parts values with &f%cmd_usage%"
  paste-all4: "&eThese are the current values:"
  undid: "&aLast part cancelled, you will now place: &l&f%part%"
  not-any-placed: "&cYou can't use that command now, you haven't placed any parts yet."
  part-not-found: "&cThe part cannot be found."
  add-to-history: "&bAdding to history..."
  validation-success: "&aThe validation process was successful."
  merging-parts: "&bMerging parts..."
  cancel-success: "&aThe abort process was successful"
  nothing-to-undo: "&cThere isn't anything to undo"
  part-placed: "&aThe part was successfully placed, the values are: "
  place-next-part: "&eYou can now place the next part &l&f(%part%) &r&ewith left click or you can cancel it with right click. (You need to have an item in your hand)"
  or-modify: "&eYou can also modify the values of the current part with &f&o%cmd_usage% &r&eYou will be able to do it later too."
